/**
 * @fileoverview Strongly-typed representation of an ASP.NET Core
 * {@link https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails|ProblemDetails}
 * error response body.
 *
 * The backend returns this JSON shape on 4xx / 5xx responses when
 * `ApiExceptionHandler` is active.
 */

/**
 * A structured error response conforming to the ProblemDetails RFC 7807
 * specification as implemented by ASP.NET Core.
 *
 * @property type     A URI reference that identifies the problem type.
 * @property title    A short, human-readable summary of the problem.
 * @property status   The HTTP status code generated by the server.
 * @property detail   A human-readable explanation specific to this occurrence.
 * @property instance A URI reference that identifies the specific occurrence.
 * @property errors   Validation errors keyed by property name (ASP.NET Core `ValidationProblemDetails`).
 */
export interface ProblemDetails {
  readonly type?: string;
  readonly title?: string;
  readonly status?: number;
  readonly detail?: string;
  readonly instance?: string;
  readonly errors?: Record<string, readonly string[]>;
}
